/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const loginBodyUsernameMin = 3;
export const loginBodyUsernameMax = 20;

export const loginBodyPasswordMin = 8;
export const loginBodyPasswordMax = 64;



export const LoginBody = zod.object({
  "username": zod.string().min(loginBodyUsernameMin).max(loginBodyUsernameMax),
  "password": zod.string().min(loginBodyPasswordMin).max(loginBodyPasswordMax)
})

export const LoginResponse = zod.object({
  "token": zod.string()
})

