/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Item
} from '../models';


export const getListItemsResponseMock = (): Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({...{name: faker.string.alpha({length: {min: 1, max: 30}}), price: faker.number.int({min: 0, max: 1000000}), category: faker.helpers.arrayElement(['food','drink','other'] as const), code: faker.helpers.fromRegExp("^[A-Z0-9]{8}$")},...{id: faker.number.int()},})))

export const getCreateItemResponseMock = (): Item => ({...{name: faker.string.alpha({length: {min: 1, max: 30}}), price: faker.number.int({min: 0, max: 1000000}), category: faker.helpers.arrayElement(['food','drink','other'] as const), code: faker.helpers.fromRegExp("^[A-Z0-9]{8}$")},...{id: faker.number.int()},})

export const getGetItemResponseMock = (): Item => ({...{name: faker.string.alpha({length: {min: 1, max: 30}}), price: faker.number.int({min: 0, max: 1000000}), category: faker.helpers.arrayElement(['food','drink','other'] as const), code: faker.helpers.fromRegExp("^[A-Z0-9]{8}$")},...{id: faker.number.int()},})

export const getUpdateItemResponseMock = (): Item => ({...{name: faker.string.alpha({length: {min: 1, max: 30}}), price: faker.number.int({min: 0, max: 1000000}), category: faker.helpers.arrayElement(['food','drink','other'] as const), code: faker.helpers.fromRegExp("^[A-Z0-9]{8}$")},...{id: faker.number.int()},})

export const getSearchItemsResponseMock = (): Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({...{name: faker.string.alpha({length: {min: 1, max: 30}}), price: faker.number.int({min: 0, max: 1000000}), category: faker.helpers.arrayElement(['food','drink','other'] as const), code: faker.helpers.fromRegExp("^[A-Z0-9]{8}$")},...{id: faker.number.int()},})))


export const getListItemsMockHandler = (overrideResponse?: Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Item[]> | Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/items', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListItemsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.post('*/items', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateItemResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.get('*/items/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.put('*/items/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteItemMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/items/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getSearchItemsMockHandler = (overrideResponse?: Item[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Item[]> | Item[]), options?: RequestHandlerOptions) => {
  return http.get('*/search', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSearchItemsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getItemsMock = () => [
  getListItemsMockHandler(),
  getCreateItemMockHandler(),
  getGetItemMockHandler(),
  getUpdateItemMockHandler(),
  getDeleteItemMockHandler(),
  getSearchItemsMockHandler()]
