/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */
import type {
  Item,
  ItemInput,
  ListItemsParams,
  SearchItemsParams
} from '../models';

import { request } from '.././axios';



  export const listItems = (
    params?: ListItemsParams,
 ) => {
      return request<Item[]>(
      {url: `/items`, method: 'GET',
        params
    },
      );
    }
  export const createItem = (
    itemInput: ItemInput,
 ) => {
      return request<Item>(
      {url: `/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: itemInput
    },
      );
    }
  export const getItem = (
    id: number,
 ) => {
      return request<Item>(
      {url: `/items/${id}`, method: 'GET'
    },
      );
    }
  export const updateItem = (
    id: number,
    itemInput: ItemInput,
 ) => {
      return request<Item>(
      {url: `/items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: itemInput
    },
      );
    }
  export const deleteItem = (
    id: number,
 ) => {
      return request<void>(
      {url: `/items/${id}`, method: 'DELETE'
    },
      );
    }
  export const searchItems = (
    params: SearchItemsParams,
 ) => {
      return request<Item[]>(
      {url: `/search`, method: 'GET',
        params
    },
      );
    }
  export type ListItemsResult = NonNullable<Awaited<ReturnType<typeof listItems>>>
export type CreateItemResult = NonNullable<Awaited<ReturnType<typeof createItem>>>
export type GetItemResult = NonNullable<Awaited<ReturnType<typeof getItem>>>
export type UpdateItemResult = NonNullable<Awaited<ReturnType<typeof updateItem>>>
export type DeleteItemResult = NonNullable<Awaited<ReturnType<typeof deleteItem>>>
export type SearchItemsResult = NonNullable<Awaited<ReturnType<typeof searchItems>>>
