/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginRequest,
  LoginResponse
} from '../models';

import { request } from '.././axios';



  export const login = (
    loginRequest: LoginRequest,
 ) => {
      return request<LoginResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>
