/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */
import type { ItemInputCategory } from './itemInputCategory';

export interface ItemInput {
  /**
     * @minLength 1
     * @maxLength 30
     */
  name: string;
  /**
     * @minimum 0
     * @maximum 1000000
     */
  price: number;
  category: ItemInputCategory;
  /** @pattern ^[A-Z0-9]{8}$ */
  code: string;
}
