/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */

export type ItemInputCategory = typeof ItemInputCategory[keyof typeof ItemInputCategory];


export const ItemInputCategory = {
  food: 'food',
  drink: 'drink',
  other: 'other',
} as const;
