/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */
import type { ItemInput } from './itemInput';

export type Item = ItemInput & {
  id: number;
};
