/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */

export type ListItemsParams = {
/**
 * @maxLength 50
 */
q?: string;
/**
 * @pattern ^[A-Z0-9]{8}$
 */
code?: string;
};
