/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequest {
  /**
     * @minLength 3
     * @maxLength 20
     */
  username: string;
  /**
     * @minLength 8
     * @maxLength 64
     */
  password: string;
}
