/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */

export type SearchItemsParams = {
/**
 * @minLength 1
 * @maxLength 50
 */
q: string;
};
