/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * ionic-vue-orval PoC API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const listItemsQueryQMax = 50;

export const listItemsQueryCodeRegExp = new RegExp('^[A-Z0-9]{8}$');


export const ListItemsQueryParams = zod.object({
  "q": zod.string().max(listItemsQueryQMax).optional(),
  "code": zod.string().regex(listItemsQueryCodeRegExp).optional()
})

export const listItemsResponseOneNameMax = 30;

export const listItemsResponseOnePriceMin = 0;
export const listItemsResponseOnePriceMax = 1000000;

export const listItemsResponseOneCodeRegExp = new RegExp('^[A-Z0-9]{8}$');


export const ListItemsResponseItem = zod.object({
  "name": zod.string().min(1).max(listItemsResponseOneNameMax),
  "price": zod.number().min(listItemsResponseOnePriceMin).max(listItemsResponseOnePriceMax),
  "category": zod.enum(['food', 'drink', 'other']),
  "code": zod.string().regex(listItemsResponseOneCodeRegExp)
}).and(zod.object({
  "id": zod.number()
}))
export const ListItemsResponse = zod.array(ListItemsResponseItem)

export const createItemBodyNameMax = 30;

export const createItemBodyPriceMin = 0;
export const createItemBodyPriceMax = 1000000;

export const createItemBodyCodeRegExp = new RegExp('^[A-Z0-9]{8}$');


export const CreateItemBody = zod.object({
  "name": zod.string().min(1).max(createItemBodyNameMax),
  "price": zod.number().min(createItemBodyPriceMin).max(createItemBodyPriceMax),
  "category": zod.enum(['food', 'drink', 'other']),
  "code": zod.string().regex(createItemBodyCodeRegExp)
})

export const GetItemParams = zod.object({
  "id": zod.number()
})

export const getItemResponseOneNameMax = 30;

export const getItemResponseOnePriceMin = 0;
export const getItemResponseOnePriceMax = 1000000;

export const getItemResponseOneCodeRegExp = new RegExp('^[A-Z0-9]{8}$');


export const GetItemResponse = zod.object({
  "name": zod.string().min(1).max(getItemResponseOneNameMax),
  "price": zod.number().min(getItemResponseOnePriceMin).max(getItemResponseOnePriceMax),
  "category": zod.enum(['food', 'drink', 'other']),
  "code": zod.string().regex(getItemResponseOneCodeRegExp)
}).and(zod.object({
  "id": zod.number()
}))

export const UpdateItemParams = zod.object({
  "id": zod.number()
})

export const updateItemBodyNameMax = 30;

export const updateItemBodyPriceMin = 0;
export const updateItemBodyPriceMax = 1000000;

export const updateItemBodyCodeRegExp = new RegExp('^[A-Z0-9]{8}$');


export const UpdateItemBody = zod.object({
  "name": zod.string().min(1).max(updateItemBodyNameMax),
  "price": zod.number().min(updateItemBodyPriceMin).max(updateItemBodyPriceMax),
  "category": zod.enum(['food', 'drink', 'other']),
  "code": zod.string().regex(updateItemBodyCodeRegExp)
})

export const updateItemResponseOneNameMax = 30;

export const updateItemResponseOnePriceMin = 0;
export const updateItemResponseOnePriceMax = 1000000;

export const updateItemResponseOneCodeRegExp = new RegExp('^[A-Z0-9]{8}$');


export const UpdateItemResponse = zod.object({
  "name": zod.string().min(1).max(updateItemResponseOneNameMax),
  "price": zod.number().min(updateItemResponseOnePriceMin).max(updateItemResponseOnePriceMax),
  "category": zod.enum(['food', 'drink', 'other']),
  "code": zod.string().regex(updateItemResponseOneCodeRegExp)
}).and(zod.object({
  "id": zod.number()
}))

export const DeleteItemParams = zod.object({
  "id": zod.number()
})

export const searchItemsQueryQMax = 50;



export const SearchItemsQueryParams = zod.object({
  "q": zod.string().min(1).max(searchItemsQueryQMax)
})

export const searchItemsResponseOneNameMax = 30;

export const searchItemsResponseOnePriceMin = 0;
export const searchItemsResponseOnePriceMax = 1000000;

export const searchItemsResponseOneCodeRegExp = new RegExp('^[A-Z0-9]{8}$');


export const SearchItemsResponseItem = zod.object({
  "name": zod.string().min(1).max(searchItemsResponseOneNameMax),
  "price": zod.number().min(searchItemsResponseOnePriceMin).max(searchItemsResponseOnePriceMax),
  "category": zod.enum(['food', 'drink', 'other']),
  "code": zod.string().regex(searchItemsResponseOneCodeRegExp)
}).and(zod.object({
  "id": zod.number()
}))
export const SearchItemsResponse = zod.array(SearchItemsResponseItem)

